// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnionMarket.Data;

#nullable disable

namespace UnionMarket.Migrations
{
    [DbContext(typeof(UnionMarketContext))]
    [Migration("20251126092205_updateShopcategory")]
    partial class updateShopcategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("products_id");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tags_id");

                    b.HasKey("ProductsId", "TagsId")
                        .HasName("pk_product_product_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_product_product_tag_tags_id");

                    b.ToTable("product_product_tag", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("row_id");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("table_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_carts_user_id");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cart_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_cart_items");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_cart_items_cart_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cart_items_product_id");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("FinalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("final_amount");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_discount");

                    b.Property<decimal?>("TotalProducts")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_products");

                    b.Property<decimal?>("TotalShipping")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_shipping");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_checkout_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_checkout_sessions_user_id");

                    b.ToTable("checkout_sessions", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("seller_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversations_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_conversations_user_id1");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.FlashSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_flash_sales");

                    b.ToTable("flash_sales", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("login_time");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_histories");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_histories_user_id");

                    b.ToTable("login_histories", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_orders_address_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shop_id");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_order_items_shop_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_histories");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_status_histories_order_id");

                    b.ToTable("order_status_histories", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payments_order_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sale_price");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shop_id");

                    b.Property<int?>("SoldCount")
                        .HasColumnType("int")
                        .HasColumnName("sold_count");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_products_shop_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attribute_name");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_product_attributes");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_attributes_product_id");

                    b.ToTable("product_attributes", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("is_main");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_images");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_images_product_id");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_product_tags");

                    b.ToTable("product_tags", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sku");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("VariantName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("variant_name");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_variants_product_id");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReporterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reporter_id");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_review");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_review_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_user_id");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keyword");

                    b.Property<DateTime?>("SearchedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("searched_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_search_histories");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_search_histories_user_id");

                    b.ToTable("search_histories", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.SellerEarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_item_id");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seller_earnings");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_seller_earnings_order_item_id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_seller_earnings_shop_id");

                    b.ToTable("seller_earnings", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("delivered_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipped_at");

                    b.Property<Guid?>("ShippingCompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipping_company_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tracking_code");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_shipments_order_id");

                    b.HasIndex("ShippingCompanyId")
                        .HasDatabaseName("ix_shipments_shipping_company_id");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.ShipmentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shipment_logs");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_shipment_logs_shipment_id");

                    b.ToTable("shipment_logs", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.ShippingCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_shipping_companies");

                    b.ToTable("shipping_companies", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cover_image");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("FollowersCount")
                        .HasColumnType("int")
                        .HasColumnName("followers_count");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo");

                    b.Property<double?>("RatingAvg")
                        .HasColumnType("float")
                        .HasColumnName("rating_avg");

                    b.Property<string>("ShopName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shop_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_shops_user_id")
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.ShopCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shop_id");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_shop_categories");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_shop_categories_shop_id");

                    b.ToTable("shop_categories", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.ShopReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shop_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shop_reviews");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_shop_reviews_shop_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_shop_reviews_user_id");

                    b.ToTable("shop_reviews", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("phone_verified_at");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("pk_user_addresses");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_addresses_user_id");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("MinOrder")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_order");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_vouchers");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_user_id")
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("UnionMarket.Models.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transactions");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_wallet_transactions_wallet_id");

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<int>("role_id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("role_id", "user_id")
                        .HasName("pk_user_roles");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_tag_products_products_id");

                    b.HasOne("UnionMarket.Models.Entities.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_tag_product_tags_tags_id");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Cart", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_carts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.CartItem", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .HasConstraintName("fk_cart_items_carts_cart_id");

                    b.HasOne("UnionMarket.Models.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_cart_items_products_product_id");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Category", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.CheckoutSession", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("CheckoutSessions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_checkout_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Conversation", b =>
                {
                    b.HasOne("UnionMarket.Models.User", null)
                        .WithMany("ConversationBuyers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_conversations_users_user_id");

                    b.HasOne("UnionMarket.Models.User", null)
                        .WithMany("ConversationSellers")
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_conversations_users_user_id1");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.LoginHistory", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_login_histories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Message", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("UnionMarket.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("fk_messages_users_sender_id");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Notification", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Order", b =>
                {
                    b.HasOne("UnionMarket.Models.UserAddress", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("fk_orders_user_addresses_address_id");

                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_orders_users_user_id");

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("UnionMarket.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.HasOne("UnionMarket.Models.Shop", "Shop")
                        .WithMany("OrderItems")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("fk_order_items_shops_shop_id");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Order", "Order")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_order_status_histories_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Payment", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_payments_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Product", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("UnionMarket.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("fk_products_shops_shop_id");

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.ProductAttribute", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_product_attributes_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.ProductImage", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_product_images_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.ProductVariant", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UnionMarket.Models.Review", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_review_products_product_id");

                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_review_users_user_id");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.SearchHistory", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_search_histories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.SellerEarning", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.OrderItem", "OrderItem")
                        .WithMany("SellerEarnings")
                        .HasForeignKey("OrderItemId")
                        .HasConstraintName("fk_seller_earnings_order_items_order_item_id");

                    b.HasOne("UnionMarket.Models.Shop", "Shop")
                        .WithMany("SellerEarnings")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("fk_seller_earnings_shops_shop_id");

                    b.Navigation("OrderItem");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("UnionMarket.Models.Shipment", b =>
                {
                    b.HasOne("UnionMarket.Models.Entities.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_shipments_orders_order_id");

                    b.HasOne("UnionMarket.Models.ShippingCompany", "ShippingCompany")
                        .WithMany("Shipments")
                        .HasForeignKey("ShippingCompanyId")
                        .HasConstraintName("fk_shipments_shipping_companies_shipping_company_id");

                    b.Navigation("Order");

                    b.Navigation("ShippingCompany");
                });

            modelBuilder.Entity("UnionMarket.Models.ShipmentLog", b =>
                {
                    b.HasOne("UnionMarket.Models.Shipment", "Shipment")
                        .WithMany("ShipmentLogs")
                        .HasForeignKey("ShipmentId")
                        .HasConstraintName("fk_shipment_logs_shipments_shipment_id");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("UnionMarket.Models.Shop", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithOne("Shop")
                        .HasForeignKey("UnionMarket.Models.Shop", "UserId")
                        .HasConstraintName("fk_shops_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.ShopCategory", b =>
                {
                    b.HasOne("UnionMarket.Models.Shop", "Shop")
                        .WithMany("ShopCategories")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("fk_shop_categories_shops_shop_id");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("UnionMarket.Models.ShopReview", b =>
                {
                    b.HasOne("UnionMarket.Models.Shop", "Shop")
                        .WithMany("ShopReviews")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("fk_shop_reviews_shops_shop_id");

                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("ShopReviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_shop_reviews_users_user_id");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.UserAddress", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_addresses_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.Wallet", b =>
                {
                    b.HasOne("UnionMarket.Models.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("UnionMarket.Models.Wallet", "UserId")
                        .HasConstraintName("fk_wallets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnionMarket.Models.WalletTransaction", b =>
                {
                    b.HasOne("UnionMarket.Models.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .HasConstraintName("fk_wallet_transactions_wallets_wallet_id");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("UnionMarket.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_roles");

                    b.HasOne("UnionMarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_users");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderStatusHistories");

                    b.Navigation("Payments");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.OrderItem", b =>
                {
                    b.Navigation("SellerEarnings");
                });

            modelBuilder.Entity("UnionMarket.Models.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("UnionMarket.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentLogs");
                });

            modelBuilder.Entity("UnionMarket.Models.ShippingCompany", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("UnionMarket.Models.Shop", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Products");

                    b.Navigation("SellerEarnings");

                    b.Navigation("ShopCategories");

                    b.Navigation("ShopReviews");
                });

            modelBuilder.Entity("UnionMarket.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CheckoutSessions");

                    b.Navigation("ConversationBuyers");

                    b.Navigation("ConversationSellers");

                    b.Navigation("LoginHistories");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("SearchHistories");

                    b.Navigation("Shop");

                    b.Navigation("ShopReviews");

                    b.Navigation("UserAddresses");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("UnionMarket.Models.UserAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("UnionMarket.Models.Wallet", b =>
                {
                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
